[about]
version = Version: 3.4.1 (Build 20260413)
copyright = Copyright © 2004 - 2026 EaseUS. All rights reserved.
active = Edition: Pro

[install]
path=C:\Program Files\EaseUS\VoiceWave\bin\easeus.voicewave.exe
;path = C:\Program Files (x86)\EaseUS\VoiceWave\bin\easeus.voicewave.exe

;[file]
;import_path=C:\Users\12693\Desktop\autotest\project\python-uiautomation-for-pc-evw\resources\支持格式文件
;output_path=C:\Users\12693\Desktop\autotest\project\python-uiautomation-for-pc-evw\resources\输出格式文件
;language_import_path=C:\Users\12693\Desktop\autotest\project\python-uiautomation-for-pc-evw\resources\导入多语言路径\
;language_output_path=C:\Users\12693\Desktop\autotest\project\python-uiautomation-for-pc-evw\resources\导出多语言路径\


[file]
import_path=F:\evwtools\project\python-uiautomation-for-pc-evw\resources\支持格式文件
output_path=F:\evwtools\project\python-uiautomation-for-pc-evw\resources\输出格式文件
language_import_path=F:\evwtools\project\python-uiautomation-for-pc-evw\resources\导入多语言路径\
language_output_path=F:\evwtools\project\python-uiautomation-for-pc-evw\resources\导出多语言路径\

[sensors]
key = K-RV2k4ZnaZ7N4LngWqvxc8keLfyKadDFM
url = https://chengduyiwokeji-haiwai.cloud.sensorsjourney.com
project = production


